spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true # to view the H2 console at http://localhost:8080/h2-console
spring.jpa.hibernate.ddl-auto=none #to disable making updates to DB structure an application startup

server.port = 8080

#to see logs of transaction management
#logging.level.org.hibernate.engine.transaction.internal.TransactionImpl=DEBUG
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG